const express = require('express');
const { PrismaClient } = require('@prisma/client');
const aiService = require('../services/aiService');
const router = express.Router();
const prisma = new PrismaClient();

// AI Roadmap Generator
router.post('/generate', async (req, res) => {
  try {
    const { year, branch, skills, goals, timeframe = 3 } = req.body;
    const userId = req.user.id;

    // Generate AI-powered roadmap
    const aiRoadmapData = await aiService.generateRoadmap({
      year,
      branch, 
      skills,
      goals,
      timeframe
    });

    // Create roadmap in database
    const roadmap = await prisma.roadmap.create({
      data: {
        userId,
        title: `AI-Generated ${branch} Career Roadmap - ${timeframe} Months`,
        description: `Personalized roadmap for ${goals} generated by AI`,
        startDate: new Date(),
        endDate: new Date(Date.now() + timeframe * 30 * 24 * 60 * 60 * 1000),
        milestones: {
          create: aiRoadmapData.milestones.map((milestone, index) => ({
            title: milestone.title,
            description: milestone.description,
            category: milestone.category,
            targetOutcome: milestone.targetOutcome,
            pros: JSON.stringify(milestone.pros || []),
            cons: JSON.stringify(milestone.cons || []),
            metrics: JSON.stringify(milestone.metrics || {}),
            actionSteps: JSON.stringify(milestone.actionSteps || []),
            deadline: new Date(Date.now() + (index + 1) * (timeframe / aiRoadmapData.milestones.length) * 30 * 24 * 60 * 60 * 1000)
          }))
        }
      },
      include: {
        milestones: true
      }
    });

    // Parse JSON strings back to objects for response
    const roadmapWithParsedData = {
      ...roadmap,
      milestones: roadmap.milestones.map(milestone => ({
        ...milestone,
        pros: JSON.parse(milestone.pros || '[]'),
        cons: JSON.parse(milestone.cons || '[]'),
        metrics: JSON.parse(milestone.metrics || '{}'),
        actionSteps: JSON.parse(milestone.actionSteps || '[]')
      }))
    };

    res.json({
      success: true,
      roadmap: roadmapWithParsedData,
      aiInsights: aiRoadmapData.insights || [
        `AI-generated roadmap based on your ${year} year ${branch} profile`,
        `Optimized for ${goals} career path`,
        `${timeframe}-month timeline with actionable milestones`
      ],
      metadata: {
        generatedBy: 'AI',
        confidence: 0.85,
        lastUpdated: new Date().toISOString()
      }
    });
  } catch (error) {
    console.error('Roadmap generation error:', error);
    res.status(500).json({ 
      error: 'Failed to generate roadmap',
      message: error.message 
    });
  }
});

// Get user's roadmaps
router.get('/my-roadmaps', async (req, res) => {
  try {
    const userId = req.user.id;
    
    const roadmaps = await prisma.roadmap.findMany({
      where: { userId },
      include: {
        milestones: {
          orderBy: { deadline: 'asc' }
        }
      },
      orderBy: { createdAt: 'desc' }
    });

    // Parse JSON strings for each roadmap
    const roadmapsWithParsedData = roadmaps.map(roadmap => ({
      ...roadmap,
      milestones: roadmap.milestones.map(milestone => ({
        ...milestone,
        pros: JSON.parse(milestone.pros || '[]'),
        cons: JSON.parse(milestone.cons || '[]'),
        metrics: JSON.parse(milestone.metrics || '{}'),
        actionSteps: JSON.parse(milestone.actionSteps || '[]')
      }))
    }));

    res.json({
      success: true,
      roadmaps: roadmapsWithParsedData
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Update milestone completion
router.patch('/milestone/:id/complete', async (req, res) => {
  try {
    const { id } = req.params;
    const { completed } = req.body;

    const milestone = await prisma.milestone.update({
      where: { id },
      data: { completed }
    });

    res.json({
      success: true,
      milestone
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;